# Generated by Django 3.2.18 on 2023-04-23 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_salesad_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesad',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
