# Generated by Django 3.2.18 on 2023-04-27 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_directmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
