# Generated by Django 3.2.18 on 2023-05-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_alter_conversationmessage_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
