# Generated by Django 3.2.18 on 2023-05-27 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0018_studygroup_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='group_admin',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
