# Generated by Django 3.2.18 on 2023-05-27 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0019_studygroup_group_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='group_admin',
            field=models.ManyToManyField(related_name='group_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
