# Generated by Django 3.2.18 on 2023-05-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_alter_studygroup_group_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='group_admin',
        ),
    ]
